# Generated by Django 5.0.6 on 2024-07-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.CharField(max_length=50, verbose_name='Названия урока')),
                ('about_lesson', models.TextField(verbose_name='Об уроке')),
                ('photo', models.FileField(blank=True, null=True, upload_to='photos/')),
            ],
            options={
                'verbose_name': 'lesson',
                'verbose_name_plural': 'lessons',
            },
        ),
        migrations.CreateModel(
            name='New_Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.CharField(max_length=50, verbose_name='Названия урока')),
                ('about_lesson', models.TextField(verbose_name='Об уроке')),
                ('photo', models.FileField(blank=True, null=True, upload_to='photos/')),
            ],
            options={
                'verbose_name': 'new lesson',
                'verbose_name_plural': 'new lessons',
            },
        ),
        migrations.CreateModel(
            name='Now_Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.CharField(max_length=50, verbose_name='Названия урока')),
                ('about_lesson', models.TextField(verbose_name='Об уроке')),
                ('photo', models.FileField(blank=True, null=True, upload_to='photos/')),
            ],
            options={
                'verbose_name': 'now lesson',
                'verbose_name_plural': 'now lessons',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='Имя фамилия')),
                ('phone_number', models.TextField()),
                ('home_address', models.TextField()),
                ('kurs', models.CharField(max_length=50, verbose_name='Курс')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('full_name', models.CharField(max_length=50, verbose_name='Имя фамилия')),
                ('telegram_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Telegram id')),
                ('username', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
