# Generated by Django 5.0.6 on 2024-07-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='photo',
            field=models.FileField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='new_lessons',
            name='photo',
            field=models.FileField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='now_lessons',
            name='photo',
            field=models.FileField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='students',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
