# Generated by Django 5.0.6 on 2024-07-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_lessons_photo_alter_new_lessons_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='home_address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='students',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
