# Generated by Django 5.0.6 on 2024-07-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_students_home_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
