# Generated by Django 5.0.6 on 2024-07-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_students_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hendlers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_kurs', models.CharField(max_length=50, verbose_name='kurslar')),
                ('msg_name', models.CharField(max_length=50, verbose_name='ism familiya')),
                ('msg_phone', models.CharField(max_length=50, verbose_name='telefon raqam')),
                ('msg_adres', models.CharField(max_length=50, verbose_name='uy manzil')),
                ('reseption', models.CharField(max_length=50, verbose_name='resepyion')),
                ('data_tel', models.CharField(max_length=50, verbose_name='data telefon raqam')),
                ('now_lessons_msg', models.CharField(max_length=50, verbose_name='hozirgi kurslar')),
                ('new_lessons_msg', models.CharField(max_length=50, verbose_name='yangi ochiladigan kurlar')),
                ('lessons_msg', models.CharField(max_length=50, verbose_name='barcha kurslar')),
                ('l_message', models.CharField(max_length=50, verbose_name='barcha kurslarimiz')),
                ('new_message', models.CharField(max_length=50, verbose_name='endi ochiladigan kurslarimiz')),
                ('now_message', models.CharField(max_length=50, verbose_name='hozirda ochiq kurlarimiz')),
                ('msg_start', models.CharField(max_length=50, verbose_name='Имя фамилия')),
            ],
            options={
                'verbose_name': 'hendler',
                'verbose_name_plural': 'hendlers',
            },
        ),
    ]
