# Generated by Django 5.0.6 on 2024-07-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_hendlers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hendlers',
            name='data_tel',
            field=models.CharField(max_length=100, verbose_name='data telefon raqam'),
        ),
        migrations.AlterField(
            model_name='hendlers',
            name='l_message',
            field=models.CharField(max_length=100, verbose_name='barcha kurslarimiz'),
        ),
        migrations.AlterField(
            model_name='hendlers',
            name='lessons_msg',
            field=models.CharField(max_length=100, verbose_name='barcha kurslar'),
        ),
        migrations.AlterField(
            model_name='hendlers',
            name='msg_adres',
            field=models.CharField(max_length=100, verbose_name='uy manzil'),
        ),
        migrations.AlterField(
            model_name='hendlers',
            name='msg_kurs',
            field=models.CharField(max_length=100, verbose_name='kurslar'),
        ),
        migrations.AlterField(
            model_name='hendlers',
            name='msg_name',
            field=models.CharField(max_length=100, verbose_name='ism familiya'),
        ),
        migrations.AlterField(
            model_name='hendlers',
            name='msg_phone',
            field=models.CharField(max_length=100, verbose_name='telefon raqam'),
        ),
        migrations.AlterField(
            model_name='hendlers',
            name='msg_start',
            field=models.CharField(max_length=100, verbose_name='Имя фамилия'),
        ),
        migrations.AlterField(
            model_name='hendlers',
            name='new_lessons_msg',
            field=models.CharField(max_length=100, verbose_name='yangi ochiladigan kurlar'),
        ),
        migrations.AlterField(
            model_name='hendlers',
            name='new_message',
            field=models.CharField(max_length=100, verbose_name='endi ochiladigan kurslarimiz'),
        ),
        migrations.AlterField(
            model_name='hendlers',
            name='now_lessons_msg',
            field=models.CharField(max_length=100, verbose_name='hozirgi kurslar'),
        ),
        migrations.AlterField(
            model_name='hendlers',
            name='now_message',
            field=models.CharField(max_length=100, verbose_name='hozirda ochiq kurlarimiz'),
        ),
        migrations.AlterField(
            model_name='hendlers',
            name='reseption',
            field=models.CharField(max_length=100, verbose_name='resepyion'),
        ),
    ]
