# Generated by Django 5.0.6 on 2024-07-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_hendlers_data_tel_alter_hendlers_l_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hendlers',
            name='msg_start',
            field=models.CharField(max_length=100, verbose_name='start'),
        ),
    ]
