# Generated by Django 5.0.6 on 2024-07-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_hendlers_msg_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot_admin',
            fields=[
                ('full_name', models.CharField(max_length=50, verbose_name='Имя фамилия')),
                ('telegram_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Telegram id')),
                ('username', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'admin',
                'verbose_name_plural': 'admins',
            },
        ),
    ]
